// Maps a free-text nationality (as stored in the DB, e.g. "USA", "United States",
// "Brazil", "Russia") to an ISO 3166-1 alpha-2 country code, used to render a flag.
// The data is messy (aliases, regions, "Unknown"), so we normalize aggressively and
// keep a generous alias table. Returns null when we can't confidently resolve a flag.

const NAME_TO_ISO2: Record<string, string> = {
  // North America
  "united states": "us",
  "united states of america": "us",
  usa: "us",
  us: "us",
  america: "us",
  american: "us",
  canada: "ca",
  canadian: "ca",
  mexico: "mx",
  mexican: "mx",

  // South / Central America
  brazil: "br",
  brasil: "br",
  brazilian: "br",
  argentina: "ar",
  argentine: "ar",
  argentinian: "ar",
  chile: "cl",
  chilean: "cl",
  peru: "pe",
  peruvian: "pe",
  colombia: "co",
  colombian: "co",
  venezuela: "ve",
  venezuelan: "ve",
  ecuador: "ec",
  uruguay: "uy",
  uruguayan: "uy",
  paraguay: "py",
  bolivia: "bo",
  cuba: "cu",
  cuban: "cu",
  "dominican republic": "do",
  dominican: "do",
  "puerto rico": "pr",
  "puerto rican": "pr",
  panama: "pa",
  panamanian: "pa",
  "costa rica": "cr",
  "costa rican": "cr",
  guatemala: "gt",
  honduras: "hn",
  "el salvador": "sv",
  nicaragua: "ni",
  jamaica: "jm",
  jamaican: "jm",
  "trinidad and tobago": "tt",
  suriname: "sr",
  guyana: "gy",

  // Western Europe
  "united kingdom": "gb",
  uk: "gb",
  "great britain": "gb",
  britain: "gb",
  british: "gb",
  england: "gb",
  english: "gb",
  scotland: "gb",
  scottish: "gb",
  wales: "gb",
  welsh: "gb",
  "northern ireland": "gb",
  ireland: "ie",
  irish: "ie",
  france: "fr",
  french: "fr",
  germany: "de",
  german: "de",
  spain: "es",
  espana: "es",
  spanish: "es",
  italy: "it",
  italia: "it",
  italian: "it",
  portugal: "pt",
  portuguese: "pt",
  netherlands: "nl",
  holland: "nl",
  dutch: "nl",
  belgium: "be",
  belgian: "be",
  switzerland: "ch",
  swiss: "ch",
  austria: "at",
  austrian: "at",
  luxembourg: "lu",
  malta: "mt",
  cyprus: "cy",

  // Nordics
  sweden: "se",
  swedish: "se",
  norway: "no",
  norwegian: "no",
  denmark: "dk",
  danish: "dk",
  finland: "fi",
  finnish: "fi",
  iceland: "is",
  icelandic: "is",

  // Eastern Europe / Caucasus / Central Asia
  russia: "ru",
  "russian federation": "ru",
  russian: "ru",
  dagestan: "ru",
  ukraine: "ua",
  ukrainian: "ua",
  poland: "pl",
  polish: "pl",
  "czech republic": "cz",
  czechia: "cz",
  czech: "cz",
  slovakia: "sk",
  slovak: "sk",
  hungary: "hu",
  hungarian: "hu",
  romania: "ro",
  romanian: "ro",
  bulgaria: "bg",
  bulgarian: "bg",
  greece: "gr",
  greek: "gr",
  croatia: "hr",
  croatian: "hr",
  serbia: "rs",
  serbian: "rs",
  "bosnia and herzegovina": "ba",
  bosnia: "ba",
  bosnian: "ba",
  slovenia: "si",
  slovenian: "si",
  montenegro: "me",
  "north macedonia": "mk",
  macedonia: "mk",
  albania: "al",
  albanian: "al",
  kosovo: "xk",
  lithuania: "lt",
  lithuanian: "lt",
  latvia: "lv",
  latvian: "lv",
  estonia: "ee",
  estonian: "ee",
  belarus: "by",
  belarusian: "by",
  moldova: "md",
  georgia: "ge",
  georgian: "ge",
  armenia: "am",
  armenian: "am",
  azerbaijan: "az",
  azerbaijani: "az",
  kazakhstan: "kz",
  kazakh: "kz",
  kyrgyzstan: "kg",
  uzbekistan: "uz",
  tajikistan: "tj",
  turkmenistan: "tm",
  mongolia: "mn",
  mongolian: "mn",

  // Middle East / North Africa
  turkey: "tr",
  turkiye: "tr",
  turkish: "tr",
  israel: "il",
  israeli: "il",
  lebanon: "lb",
  jordan: "jo",
  "saudi arabia": "sa",
  "united arab emirates": "ae",
  uae: "ae",
  iran: "ir",
  iranian: "ir",
  iraq: "iq",
  syria: "sy",
  palestine: "ps",
  kuwait: "kw",
  qatar: "qa",
  bahrain: "bh",
  oman: "om",
  yemen: "ye",
  egypt: "eg",
  egyptian: "eg",
  morocco: "ma",
  moroccan: "ma",
  algeria: "dz",
  algerian: "dz",
  tunisia: "tn",
  tunisian: "tn",
  libya: "ly",

  // Sub-Saharan Africa
  nigeria: "ng",
  nigerian: "ng",
  cameroon: "cm",
  cameroonian: "cm",
  "south africa": "za",
  "south african": "za",
  ghana: "gh",
  ghanaian: "gh",
  kenya: "ke",
  kenyan: "ke",
  "democratic republic of the congo": "cd",
  "dr congo": "cd",
  congo: "cd",
  angola: "ao",
  angolan: "ao",
  senegal: "sn",
  "ivory coast": "ci",
  "cote d'ivoire": "ci",
  ethiopia: "et",
  tanzania: "tz",
  uganda: "ug",
  zimbabwe: "zw",
  mozambique: "mz",
  mauritius: "mu",

  // Asia / Oceania
  china: "cn",
  chinese: "cn",
  japan: "jp",
  japanese: "jp",
  "south korea": "kr",
  korea: "kr",
  "republic of korea": "kr",
  korean: "kr",
  "north korea": "kp",
  thailand: "th",
  thai: "th",
  vietnam: "vn",
  vietnamese: "vn",
  philippines: "ph",
  filipino: "ph",
  indonesia: "id",
  indonesian: "id",
  malaysia: "my",
  malaysian: "my",
  singapore: "sg",
  myanmar: "mm",
  cambodia: "kh",
  laos: "la",
  india: "in",
  indian: "in",
  pakistan: "pk",
  pakistani: "pk",
  bangladesh: "bd",
  "sri lanka": "lk",
  nepal: "np",
  afghanistan: "af",
  afghan: "af",
  australia: "au",
  australian: "au",
  "new zealand": "nz",
  samoa: "ws",
  samoan: "ws",
  tonga: "to",
  tongan: "to",
  fiji: "fj",
  fijian: "fj",
  guam: "gu",
};

function normalize(value: string): string {
  return value
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "") // strip accents
    .toLowerCase()
    .replace(/\./g, "")
    .replace(/\s+/g, " ")
    .trim();
}

/** Resolve a nationality string to an ISO 3166-1 alpha-2 code (lowercase), or null. */
export function nationalityToCountryCode(nationality: string | null | undefined): string | null {
  if (!nationality) return null;
  const key = normalize(nationality);
  if (!key || key === "unknown" || key === "n/a" || key === "-") return null;
  return NAME_TO_ISO2[key] ?? null;
}
